default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: jamradio_development

test:
  <<: *default
  database: jamradio_test

production:
  <<: *default
  database: jamradio_production
  username: jamradio
  password: <%= ENV['JAMRADIO_DATABASE_PASSWORD'] %>
